UserParameter=postfix.pfmailq,/usr/local/bin/check_mailq
UserParameter=postfix[*],sudo /usr/local/sbin/zabbix_postfix_passive.sh $1
UserParameter=postfix.update_data,sudo /usr/local/sbin/zabbix_postfix_passive.sh
